# Generated by Django 3.0.5 on 2020-05-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsapi', '0004_auto_20200505_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='idno',
            field=models.CharField(default='6AKYK17G1', max_length=9, unique=True),
        ),
    ]
