# Generated by Django 3.0.5 on 2020-05-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsapi', '0005_auto_20200505_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='idno',
            field=models.CharField(default='KA2NGBVA8', max_length=9, unique=True),
        ),
    ]
